sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
    secure: a5fiwG+8UmPWhwEtoC5+5HoeaXwaFfDEDP+cisvsiHRAo4Z+iF6P5uy3sVwKF45AAHpUsMc1UAKJz4uyZTukXeHGj8KvaNtSAJ2bB+u5sCxiulj49bFaNLoE1toa27RsdexJhF+a7iAz+YJ67QjTAMCImNA9NoqHQvSRibeMHs0RCjJxMzyFj+AdjwQHfzzQwmHriGe6E1BcyFbszSeG6cHVGnd8qi1TkRuQZw1n1gbABPYCUxFA1ytEA/6MdQwdRZ1iXBB8aQ7CjPA1CI02ogMO0JhdG7pp0fTgFZsNuMCdm5kCENpwU26Q96YQAyJymj9C3HW//Ml4TUnJsTmz+qf3DCc3D5pPcsbOcEyHrgFFY6H1dygUsObSYOWaWtB31K+VLS1n8eAPtNPfpQwofUFKX+eyuFFX0nZjIMllWp0H0hKkoS3GS/SIVsr+MGwMxogf9JB+7pbx9lpqXl4WaxYnJ10z05kHDSV2CmAEH4qmC48c5xfTbBOUnYVtWGYdzb5YqhnwVq9fm0iZA6++284+hCvhXbUWyv7MjB5X9iFeX2pIv8QOWaIzRWpSBaFNAt78QYkY1y2Wpyx9WhCSxF1S1nxqi5Q+XpFH4HdQyZCqgiVks+UMAsdFhSySSHnDZ1+aEihYa+1S6Ts03f6/BCzPMR/cpFCaXHZjcJyNuGE=
    secure: TYQf3C2w6/XmhVqpagILwD8oeLpr6FNa9iHJdn5TN0juH1MAPOeJ6BICdo2dkuzlNDa0igpWIZTuTOaPNp+c/BrY0EmmzYE1IU+3OeLWcEP8FXqTOwrVgnyHeFckhUUffw2Le5BfCDS9W+wayy/IqG7fEyytMDnfM4Gd6DEigkGXv+rDUgGIfui0t0T4MQsj0jcy/YxhSX8e8Rq16wCuyPwDt1KUTCOHh5iulFpkB0q4L8y2+FHRthyLkM9eCm5gujWj+gjBSIrmOLnsSPfHs2/Jku3W4S77jCljYpSq3gJ29ylfu8LmZjIdXtcV77d5QyCsKPbf31RvtxAcd7sYrEQvGs0WfkEG2x/9gBzA2jmWrZydy/eyboO/0K8F0fzHHUzPmPErhXiR6dMMLwaEi8Q0NzK1PCeHsp15aVpY3liFp/CVpWkEJ4fjkeNUiGSRb3j9QOtTHeJGF8ALRmoq7lUQQxsNtSjCwmeb3fI+yrQzsOp4lZmctT8T6D+voN0fePpxpoBamIaPhXKmNulAjXtu0JXDKj5TqGIREjXTILOyFJmhsS2vi2yYKoKXgfmEaoCiAuddxz2gA5jYHlLe+OHJGOEtm6fjszgp4qPcXyR8uEy6yhrK+pZsvhTnw3uDFNWWZWhCr6D0uldFxTFyTrlWfe2ltroqdFIbjmKbS0k=
before_install:
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password" -in id_rsa.enc -out deploy_key -d; fi
after_success:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
