sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: TuaOhpJUMls8xtufjSlixhyPzeMJNZarX7qqF2S30rHsuc24CMI88qdzfAZYLqWWKUnI+X28Wga8IBau+MU8BAvhuoczTvcC2EB/gHlNeFVGWpTY7SqtlgxJKgylfxMzJl7Y2bCmt3nuNjPx2Z1y/rfenUS3EnNQakScNUfKetvE2xnvI66+YuTCMNheYTjq82/eUooTCL/ONrSEENATtredTenDAgrPGnsSZtakrya1RFWmxPCk9GhOhh0DjHp/DIz4Cuqrf0/vTdDWQD7uHX4f0VlWJqAz0dE976LHwJMZqjreOziHjILadIrpgRltKBw1qMptLy3Qe1Mcnf/HJJ9mL/djYqouAMAwbT6sX7hXR4BYBhxysn1xn4eH1DNMzc48Z8ZcYYTWZuJL66FhF5nuUBLjqUeq7hv12YBOAcKIGn9dzRHTGeKIx91dW8R00y9BTJ8DdBNqz9o6f1dgFG87d02uzHVPCEo5//1gv51Suau0Hjvt+XDXUvrwbrFYLOJZM/iNNF4YeoyffIkWDZBJM7sEx30aMTfrz8+eC0cHva7aBbsVCycVkHOo7EbyQh5w6I3f+3Y/0SP5geqpIYsZLk05xFAO9MOXrpXcAloYY3PgknzM/3f4lNh5PuVQtO5Bjskq/K/PX7OEmgOcd53DZF+V2cRZoZdzp+kalNU=
  - secure: Bu0ZlYMwl9cKl0qxfo/pv0bx6ueGrYuItAODJw5abVPmQcVFs7vNx5VLeBZNcthklRt7BYQxiRTc1acAsCfB+wPmF8WxrdJ0rd42LHRv8n3rmGAg5CbdPxj7KMTgOKBbtmFeYDj7XuwPRnaP8Io2qjyrNVYN48M40abuzNa5emMSxIPdVGEBLcRhtdA+aEVl+91UxF+JFUae79ceE3aIbZ+ZH9Q55QmaQs+8doiCCW1luLocOVEr8DqS/eGebJYlWEelQCMaq76lOQOSchqDaB4pu/spxK3dsanT9cbNN5W+/XAa0E8AzLZf93i2UXXOLwf7/OWbp+RFoAhCSq2SbcIBRho909ABs8TIXa+ROx3E2WhQ5+hEIauy+RzUDwlvrz69bwoaP6x8CMkiu1hgjHCC6Er/sWQPnRJHaCZhgwvDJz2wgGOZ2wMfaAn0Zkd5kdcRFxhPf3njS3x05o0vpRNr92ojYJ1EDVGSGJ+3XGx8h45WINlX58fadzFsfYNqzQhthP71RrHW5rcLUtFGdiwrj/WdKB4+fJUvs1Y5QDKQzyCWQVuT6QkZSc+VFRG/bqfSzXuImyAMCA30tYxgKpDLa3szJf83g/niN6/4UrjF/oryMAT5KHEx9mXXVg1BBNY9mYATuP8rcHHpUbHivRkxY2hpHnMa+QV0dfgQRs4=
