sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: scoKtNbMXfyv1RDb6Q6sUu/lE5s+p8JepUQOuhB7DNxUoKp+ZfvEQ3po0Nrg3bq1niyFIwmjIBUSapJg8XKuhNe4WGYQ/uFPCAnMj3gpFPH4PYOrWCytj8DyXD3NYLwGUMmr/LgTAQvwWTTf/FluakhfwaQHjKmV0A44zs+X1xdXSbYjqcQJ/bcMTkEbnXcIiVsowqInijfLky9YDl0T31yj4E8bMoHEW00ydaqbsM9U8GDHVI1orNJDhmWNRAYiIAvEvWsWakf0ORL6DZTsMURgk65jOpNTLuWWz9/U/Eu8jzze/DkZ8tjo6IYa3vHpGWdtDg2HsbGUxDV9kzVHtFRigNUeYS6oNss0nEkzV/UHewX2qOI5jpfIzikMgLNgXpcLb52nh5o0Fcl7G2ZXSq0F8dMrp6T3yzFqYWPZETO4D1icmrqzUeQbl+++gt1YxMkSeiiD+8Xst8BIUM5MNlLvRB9DNUtBE1MKmNiGx2kh/joyrONSBjHPkE5lKRmbmk6T4Y4h7T07ByyznX2AtqQtRc6THWdHI9ttgd6w50PdEu7D1bsDi8r4neBWEABStPf72gtjCMbSd4kiGBmzEXtetKrpQ1KYHfD35uk/k640T/xs8dLTs56SHBpd9m3/ESzOHn7yLZDZnoVeRUQ2pm0Ed8LFm03WZHCzMMeeB2U=
  - secure: AwG8lcAJ+14LCMEcVI041nQRJQPyQM+K+/UUu+HSSgK9wmNULx5D4A0aDXqetnZl50tnpfCMLvpgZOlc4z/G6k/XY4qNHZB5aj2ZZI+d+cHZiJ+4DdeDwj9NbBRSE2VvpN+o8lKBt4V2jb9uwrva4xdvW9dzccHLGBPnE+oA5Fx64Qs8JDTSH98Rz7I4oKC3GvvbKsa6rNwcKbfpsR2D02cWtlR5eCo67aBDNN8CM/PsjoesYAVfZTJ95yoi/EOu2qMGbNLakJ+WYpMxdEwRnuvse9maMzVJn39/QPB/j+M8Pe/hPPg/rSzO2YyLrE35M1d8W21i0zlbFtoUICYZWUZ+pEZxLEnWEsXztssdy2RjtES94IC9zZ3Y3vymoq7CkR8pLV2A3mQsJZiIHAh/6A1Kjwf7UU30Zni/igY+7tiK17YPCn1wmj6Jq7GYafYmiZcZpGE4GOXEyIXjUPirPwnqBojKSiGiZeBwK4nxhlerJ4lHng+GVWb3uH38b3ifPt8pnGw77Oi54CswhJ49LWowfoPX6xSwj2QF4b4/Wn4A8zeeqHy9ltA93vB1GiISfsjT1X9kjq7N0iJQ+Upv9ir/A3NQ5XZnC5ppzoBvNd2loZGbyCxU9eZUZoDO3ePhMPJ1gbi+pgdx2lLmcHEzNhyZAP8bHvZ4iFOBIsR/ldw=
before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password"
  -in id_rsa.enc -out deploy_key -d; fi
after_success:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
